### ISSUE TITLE
Phrase rsalz-uta-require-tls13 in terms of minimum TLS version

### ISSUE THREAD

**Issue by davidben** [tlswg/tls12-frozen#1]
Suggest saying something to the effect of:

* A new protocol (i.e. with no legacy deployment base) SHOULD set the minimum TLS version to TLS 1.3 or higher, so that prior versions of TLS will not be negotiated.
* If deployment considerations are a concern, the protocol MAY instead set the minimum version to TLS 1.2. However, doing so means deficiencies in TLS 1.2, such as a lack of post-quantum algorithms, will apply to some uses of the protocol, and the protocol will likely have a transition in its future.

**Comment by richsalz** [comment]
Do we need this in this document, or is the UTA "use 1.3" draft enough?
See https://mailarchive.ietf.org/arch/msg/uta/Kl7iUbsILgVlgw8V4iLU_Ly5nq8/

**Comment by davidben** [comment]
This is about UTA document. It's the bug I filed after the discussion at IETF 119.

I filed it here because draft-rsalz-uta-require-tls13-00 (which was current at the time), pointed to https://github.com/richsalz/tls12-frozen, which has no issue tracker but pointed to https://github.com/tlswg/tls12-frozen. And, up until c906ddcf6ab0dbfb50a42e616b914ee5257d7bac, that document seemed to live in this repo.

I did find that a bit confusing, which is why I named the draft in the issue title. :smile:

**Comment by richsalz** [comment]
Yeah, we split up the initial draft into two drafts, and then the "call for adoption" was out of sync.  It's fixed now.  I'll close this, but please take a look at the "protocols and applications" section of https://github.com/richsalz/draft-use-tls13 and see if it captures your suggestion.  I'll close this one, and feel free to open one in the other repo :)
